### PR TITLE
Visual changes 

### LINKED ISSUE #184: Take side into account when doing splitting
When selecting split on the top screen (or left part when doing vertical) the new split should end up in that position instead of always being at the bottom (as seen in the horizontal case) 

split_placement

### LINKED ISSUE #186: Sometimes holes are created in the docking
For some reasons "holes" gets left inside the docking when making a number of splits/view deletes/etc. No clear repro steps than trying to create lots of splits, delete some, create some new, etc.

### PR DESCRIPTION
**Pull request by SlNPacifist**
Implements #189 
Implements #187 
Fixes #186 
Fixes #184 

This version is ready-to-use, however, it lacks test coverage and documentation.

Upd: it also contains some debug code. Do you need this PR for code review or you want to use it right now?

### CODE REVIEW

File: src/prodbg/main/src/windows.rs [hunk 1]
```diff
@@ -150,6 +175,7 @@ impl Windows {
                   sessions: &mut Sessions,
                   view_plugins: &mut ViewPlugins,
                   backend_plugins: &mut BackendPlugins) {
+        sleep(Duration::from_millis(100));
```
Comment (emoon) [inline src/prodbg/main/src/windows.rs]: Why is this here? It make the UI quite laggy.

Comment (SlNPacifist) [inline src/prodbg/main/src/windows.rs]: It is part of debug code as mentioned earlier. Without FPS restriction
prodbg eats one core just for to update interface.

2016-07-04 17:40 GMT+08:00 Daniel Collin <notifications@github.com>:

Comment (emoon) [inline src/prodbg/main/src/windows.rs]: But sleeping for 100 ms lowers the framerate to 10 fps. Sleeping for 1 ms is likely more reasonable.

Comment (SlNPacifist) [inline src/prodbg/main/src/windows.rs]: This code should not be here. It is only used to make debugging easier for
me. Main.rs should limit the framerate, not the windows.

2016-07-04 17:48 GMT+08:00 Daniel Collin <notifications@github.com>:

Comment (emoon) [inline src/prodbg/main/src/windows.rs]: Agreed.

Comment (SlNPacifist) [inline src/prodbg/main/src/windows.rs]: Please tell me, do you need this code to inspect it (to make sure it does
what you want and how you want) or to use it in master right now (in which
case I'll remove all the debug code right now)?

2016-07-04 18:34 GMT+08:00 Daniel Collin <notifications@github.com>:

Comment (emoon) [inline src/prodbg/main/src/windows.rs]: The point of this branch is to have the changes here before merging it into master (I have filed a bunch of bugs I found when testing) that I would like to be fixed before merge to master. I will also have some more people testing it. You can of course have the 100 ms sleep around until we decide to merge to master.
